"use client";
import { useEffect, useMemo, useState } from "react";
type Song = { album: string; song_title: string; year: number; lyrics: string };
type Theme = { name: string; color: string; words: string[] };
const THEMES: Theme[] = [
  { name: "Isolation", color: "#fa4f66", words: ["alone","lonely","wall","walls","inside","outside","stranger","empty","lost","apart","isolation"] },
  { name: "War & Power", color: "#ff9a3d", words: ["war","soldier","gun","guns","bomb","fight","enemy","power","king","death","dead","battle"] },
  { name: "Time & Mortality", color: "#f4d35e", words: ["time","years","old","age","life","death","die","dying","clock","day","days","past"] },
  { name: "Mind & Madness", color: "#aa7dff", words: ["mind","brain","mad","crazy","head","dream","dreams","fear","insane","thought","thoughts"] },
  { name: "Nature & Cosmos", color: "#62d3b4", words: ["sun","moon","star","stars","sky","river","sea","earth","wind","rain","flower","space"] },
  { name: "Love & Connection", color: "#5caeff", words: ["love","heart","together","you","friend","friends","touch","hold","home","mother","father"] },
];
function parseCSV(text: string): Song[] {
  const rows: string[][]=[]; let row:string[]=[]; let cell=""; let quoted=false;
  for(let i=0;i<text.length;i++){const ch=text[i]; if(ch==='"'){if(quoted&&text[i+1]==='"'){cell+='"';i++;}else quoted=!quoted;}else if(ch===","&&!quoted){row.push(cell);cell="";}else if((ch==="\n"||ch==="\r")&&!quoted){if(ch==="\r"&&text[i+1]==="\n")i++;row.push(cell);if(row.some(Boolean))rows.push(row);row=[];cell="";}else cell+=ch;}
  if(cell||row.length){row.push(cell);rows.push(row);} return rows.slice(1).map(r=>({album:r[0],song_title:r[1],year:Number(r[2]?.slice(0,4)),lyrics:r[3]||""})).filter(s=>s.year);
}
function score(lyrics:string,theme:Theme){const tokens=lyrics.toLowerCase().match(/[a-z']+/g)||[];if(!tokens.length)return 0;const set=new Set(theme.words);return tokens.reduce((n,w)=>n+(set.has(w)?1:0),0)/tokens.length*100;}
export default function Home(){
  const [songs,setSongs]=useState<Song[]>([]); const [active,setActive]=useState(()=>new Set(THEMES.map(t=>t.name))); const [selectedYear,setSelectedYear]=useState(1979);
  useEffect(()=>{fetch(new URL("pink_floyd_lyrics.csv",document.baseURI)).then(r=>r.text()).then(t=>setSongs(parseCSV(t)));},[]);
  const years=useMemo(()=>Array.from(new Set(songs.map(s=>s.year))).sort((a,b)=>a-b),[songs]);
  const series=useMemo(()=>THEMES.map(theme=>({theme,points:years.map(year=>{const m=songs.filter(s=>s.year===year);return{year,value:m.reduce((n,s)=>n+score(s.lyrics,theme),0)/Math.max(m.length,1)};})})),[songs,years]);
  const yearSongs=songs.filter(s=>s.year===selectedYear); const yearScores=THEMES.map(theme=>({theme,value:yearSongs.reduce((n,s)=>n+score(s.lyrics,theme),0)/Math.max(yearSongs.length,1)})).sort((a,b)=>b.value-a.value); const max=Math.max(1,...series.flatMap(s=>s.points.map(p=>p.value)));
  const firstYear=years[0]||1967; const lastYear=years.at(-1)||2014; const yearSpan=Math.max(lastYear-firstYear,1);
  const xFor=(year:number)=>(year-firstYear)/yearSpan*1000; const yFor=(value:number)=>(1-value/max)*360;
  const axisYears=[firstYear,years[Math.floor((years.length-1)*.25)]||1975,years[Math.floor((years.length-1)*.5)]||1983,years[Math.floor((years.length-1)*.75)]||1994,lastYear];
  return <main>
    <header className="topbar"><div className="brand"><span className="prism"/>THE LYRIC PRISM</div><div className="meta">PINK FLOYD · 1967—2014</div><a href="#method">HOW IT WORKS ↗</a></header>
    <section className="intro"><p className="eyebrow">AN INTERACTIVE DISCOGRAPHY STUDY</p><h1>How Pink Floyd&apos;s<br/><em>inner world</em> changed.</h1><p className="lede">Trace six recurring themes through 47 years of lyrics—from cosmic wonder and fractured minds to walls, war, time, and human connection.</p><div className="stats"><div><b>{songs.length||"—"}</b><span>SONGS ANALYZED</span></div><div><b>{years.length||"—"}</b><span>RELEASE YEARS</span></div><div><b>6</b><span>LYRICAL THEMES</span></div></div></section>
    <section className="explorer"><div className="explorerHead"><div><p className="eyebrow">01 · THE LONG VIEW</p><h2>Theme intensity over time</h2></div><p>Select themes to compare. Values show keyword frequency per 100 words across all songs released that year.</p></div><div className="themeButtons">{THEMES.map(t=><button key={t.name} className={active.has(t.name)?"active":""} onClick={()=>setActive(a=>{const n=new Set(a);n.has(t.name)?n.delete(t.name):n.add(t.name);return n;})}><i style={{background:t.color}}/>{t.name}</button>)}</div>
      <div className="chartWrap"><div className="yLabel">MENTIONS / 100 WORDS</div><div className="chart" role="img" aria-label="Line chart showing lyric theme keyword mentions per 100 words by release year">{[0,1,2,3,4].map(n=><div key={n} className="grid" style={{bottom:`${n*25}%`}}><span>{(max*n/4).toFixed(1)}</span></div>)}<svg className="chartLines" viewBox="0 0 1000 360" preserveAspectRatio="none" aria-hidden="true">{series.filter(s=>active.has(s.theme.name)).map(({theme,points})=><g key={theme.name}><polyline points={points.map(p=>`${xFor(p.year)},${yFor(p.value)}`).join(" ")} fill="none" stroke={theme.color} strokeWidth="2.5" vectorEffect="non-scaling-stroke" strokeLinejoin="round" strokeLinecap="round"/>{points.map(p=><circle key={p.year} cx={xFor(p.year)} cy={yFor(p.value)} r="3.5" fill="#0b0d12" stroke={theme.color} strokeWidth="2" vectorEffect="non-scaling-stroke"/>)}</g>)}</svg><div className="cursor" style={{left:`${xFor(selectedYear)/10}%`}}><span>{selectedYear}</span></div><input aria-label="Select a year from 1967 to 2014" type="range" min={firstYear} max={lastYear} step="1" value={selectedYear} onChange={e=>setSelectedYear(Number(e.target.value))}/></div><div className="xYears">{axisYears.map((year,i)=><span key={`${year}-${i}`}>{year}</span>)}</div></div>
    </section>
    <section className="snapshot"><div className="yearBlock"><p className="eyebrow">02 · YEAR IN FOCUS</p><div className="bigYear">{selectedYear}</div><p>{yearSongs.length} song{yearSongs.length===1?"":"s"} across {new Set(yearSongs.map(s=>s.album)).size} release{new Set(yearSongs.map(s=>s.album)).size===1?"":"s"}</p></div><div className="rankings">{yearScores.map((s,i)=><div className="rank" key={s.theme.name}><span>{String(i+1).padStart(2,"0")}</span><i style={{background:s.theme.color}}/><b>{s.theme.name}</b><div><i style={{width:`${s.value/Math.max(yearScores[0]?.value||1,1)*100}%`,background:s.theme.color}}/></div><strong>{s.value.toFixed(2)}</strong></div>)}</div><div className="songs"><p className="eyebrow">SONGS FROM THIS YEAR</p>{yearSongs.slice(0,6).map(s=><div key={s.song_title}><b>{s.song_title}</b><span>{s.album}</span></div>)}{!yearSongs.length&&<p>Move the timeline to a release year.</p>}</div></section>
    <section className="method" id="method"><p className="eyebrow">03 · METHOD</p><h2>A lens, not a verdict.</h2><p>This exploratory analysis matches curated theme vocabularies against the supplied lyrics, then normalizes counts by word total. It reveals broad patterns—not definitive interpretations. Toggle themes and move through release years to form your own reading.</p></section><footer><div className="brand"><span className="prism"/>THE LYRIC PRISM</div><span>BUILT FROM THE PINK FLOYD LYRICS DATASET</span><span>1967—2014</span></footer>
  </main>;
}
